// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AspNetUser struct {
	Id                   pgtype.UUID        `db:"Id" json:"Id"`
	Name                 string             `db:"Name" json:"Name"`
	CPF                  string             `db:"CPF" json:"CPF"`
	Email                pgtype.Text        `db:"Email" json:"Email"`
	PasswordHash         pgtype.Text        `db:"PasswordHash" json:"PasswordHash"`
	AccessFailedCount    int32              `db:"AccessFailedCount" json:"AccessFailedCount"`
	OnboardingCompleted  bool               `db:"OnboardingCompleted" json:"OnboardingCompleted"`
	LockoutEnd           pgtype.Timestamptz `db:"LockoutEnd" json:"LockoutEnd"`
	LockoutEnabled       bool               `db:"LockoutEnabled" json:"LockoutEnabled"`
	TwoFactorEnabled     bool               `db:"TwoFactorEnabled" json:"TwoFactorEnabled"`
	EmailConfirmed       bool               `db:"EmailConfirmed" json:"EmailConfirmed"`
	PhoneNumberConfirmed bool               `db:"PhoneNumberConfirmed" json:"PhoneNumberConfirmed"`
}

type CvEvaluation struct {
	Id             pgtype.UUID        `db:"Id" json:"Id"`
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	GeneratedCvId  pgtype.UUID        `db:"GeneratedCvId" json:"GeneratedCvId"`
	Liked          bool               `db:"Liked" json:"Liked"`
	Feedback       pgtype.Text        `db:"Feedback" json:"Feedback"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

type GeneratedCv struct {
	Id             pgtype.UUID        `db:"Id" json:"Id"`
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	UrlFile        string             `db:"UrlFile" json:"UrlFile"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

type GeneratedCvsNew struct {
	Id             pgtype.UUID        `db:"Id" json:"Id"`
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	JobId          pgtype.UUID        `db:"JobId" json:"JobId"`
	FileName       string             `db:"FileName" json:"FileName"`
	ExtractedText  string             `db:"ExtractedText" json:"ExtractedText"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

type Job struct {
	Id             pgtype.UUID        `db:"Id" json:"Id"`
	PlataformJobId string             `db:"PlataformJobId" json:"PlataformJobId"`
	Title          string             `db:"Title" json:"Title"`
	Description    string             `db:"Description" json:"Description"`
	Url            string             `db:"Url" json:"Url"`
	IsApplied      bool               `db:"IsApplied" json:"IsApplied"`
	Status         string             `db:"Status" json:"Status"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
	Platform       string             `db:"Platform" json:"Platform"`
	Company        string             `db:"Company" json:"Company"`
}

type JobEvaluation struct {
	Id             pgtype.UUID        `db:"Id" json:"Id"`
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	JobId          pgtype.UUID        `db:"JobId" json:"JobId"`
	Liked          bool               `db:"Liked" json:"Liked"`
	Feedback       pgtype.Text        `db:"Feedback" json:"Feedback"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

type SearchQuery struct {
	Id             pgtype.UUID        `db:"Id" json:"Id"`
	Query          string             `db:"Query" json:"Query"`
	Keywords       []string           `db:"Keywords" json:"Keywords"`
	Area           string             `db:"Area" json:"Area"`
	NormalizedHash string             `db:"NormalizedHash" json:"NormalizedHash"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
	LastExecutedAt pgtype.Timestamptz `db:"LastExecutedAt" json:"LastExecutedAt"`
	Levels         []string           `db:"Levels" json:"Levels"`
}

type UserCv struct {
	Id             pgtype.UUID        `db:"Id" json:"Id"`
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	UrlFile        string             `db:"UrlFile" json:"UrlFile"`
	ExtractedText  string             `db:"ExtractedText" json:"ExtractedText"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

type UserPreference struct {
	Id             pgtype.UUID        `db:"Id" json:"Id"`
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	Skills         []string           `db:"Skills" json:"Skills"`
	Area           string             `db:"Area" json:"Area"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
	Levels         []string           `db:"Levels" json:"Levels"`
}

type UserSearchQuery struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	SearchQueryId  pgtype.UUID        `db:"SearchQueryId" json:"SearchQueryId"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LimitedUntil   pgtype.Timestamptz `db:"LimitedUntil" json:"LimitedUntil"`
	SavedJobsCount int32              `db:"SavedJobsCount" json:"SavedJobsCount"`
}
