// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Author struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
	Cpf  string `db:"cpf" json:"cpf"`
}
