// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO "AspNetUsers" ("Name", "CPF", "Email", "PasswordHash", "AccessFailedCount", "OnboardingCompleted", "TwoFactorEnabled", "EmailConfirmed", "PhoneNumberConfirmed", "LockoutEnabled")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateUserParams struct {
	Name                 string      `db:"Name" json:"Name"`
	CPF                  string      `db:"CPF" json:"CPF"`
	Email                pgtype.Text `db:"Email" json:"Email"`
	PasswordHash         pgtype.Text `db:"PasswordHash" json:"PasswordHash"`
	AccessFailedCount    int32       `db:"AccessFailedCount" json:"AccessFailedCount"`
	OnboardingCompleted  bool        `db:"OnboardingCompleted" json:"OnboardingCompleted"`
	TwoFactorEnabled     bool        `db:"TwoFactorEnabled" json:"TwoFactorEnabled"`
	EmailConfirmed       bool        `db:"EmailConfirmed" json:"EmailConfirmed"`
	PhoneNumberConfirmed bool        `db:"PhoneNumberConfirmed" json:"PhoneNumberConfirmed"`
	LockoutEnabled       bool        `db:"LockoutEnabled" json:"LockoutEnabled"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Name,
		arg.CPF,
		arg.Email,
		arg.PasswordHash,
		arg.AccessFailedCount,
		arg.OnboardingCompleted,
		arg.TwoFactorEnabled,
		arg.EmailConfirmed,
		arg.PhoneNumberConfirmed,
		arg.LockoutEnabled,
	)
	return err
}

const createUserPreferences = `-- name: CreateUserPreferences :exec
INSERT INTO "UserPreferences" ("UserId", "Skills", "Levels", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateUserPreferencesParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	Skills         []string           `db:"Skills" json:"Skills"`
	Levels         []string           `db:"Levels" json:"Levels"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, createUserPreferences,
		arg.UserId,
		arg.Skills,
		arg.Levels,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const evaluateCv = `-- name: EvaluateCv :exec
INSERT INTO "CvEvaluations" ("UserId", "GeneratedCvId", "Liked", "Feedback", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type EvaluateCvParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	GeneratedCvId  pgtype.UUID        `db:"GeneratedCvId" json:"GeneratedCvId"`
	Liked          bool               `db:"Liked" json:"Liked"`
	Feedback       pgtype.Text        `db:"Feedback" json:"Feedback"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) EvaluateCv(ctx context.Context, arg EvaluateCvParams) error {
	_, err := q.db.Exec(ctx, evaluateCv,
		arg.UserId,
		arg.GeneratedCvId,
		arg.Liked,
		arg.Feedback,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const evaluateJob = `-- name: EvaluateJob :exec
INSERT INTO "JobEvaluations" ("UserId", "JobId", "Liked", "Feedback", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type EvaluateJobParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	JobId          pgtype.UUID        `db:"JobId" json:"JobId"`
	Liked          bool               `db:"Liked" json:"Liked"`
	Feedback       pgtype.Text        `db:"Feedback" json:"Feedback"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) EvaluateJob(ctx context.Context, arg EvaluateJobParams) error {
	_, err := q.db.Exec(ctx, evaluateJob,
		arg.UserId,
		arg.JobId,
		arg.Liked,
		arg.Feedback,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const existsCvEvaluation = `-- name: ExistsCvEvaluation :one
SELECT EXISTS (
    SELECT 1
    FROM "CvEvaluations"
    WHERE "UserId" = $1 AND "GeneratedCvId" = $2
) AS "exists"
`

type ExistsCvEvaluationParams struct {
	UserId        pgtype.UUID `db:"UserId" json:"UserId"`
	GeneratedCvId pgtype.UUID `db:"GeneratedCvId" json:"GeneratedCvId"`
}

func (q *Queries) ExistsCvEvaluation(ctx context.Context, arg ExistsCvEvaluationParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsCvEvaluation, arg.UserId, arg.GeneratedCvId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsJobEvaluation = `-- name: ExistsJobEvaluation :one
SELECT EXISTS (
    SELECT 1
    FROM "JobEvaluations"
    WHERE "UserId" = $1 AND "JobId" = $2
) AS "exists"
`

type ExistsJobEvaluationParams struct {
	UserId pgtype.UUID `db:"UserId" json:"UserId"`
	JobId  pgtype.UUID `db:"JobId" json:"JobId"`
}

func (q *Queries) ExistsJobEvaluation(ctx context.Context, arg ExistsJobEvaluationParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsJobEvaluation, arg.UserId, arg.JobId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUserByEmail = `-- name: ExistsUserByEmail :one
SELECT EXISTS (
    SELECT 1
    FROM "AspNetUsers"
    WHERE "Email" = $1
) AS "exists"
`

func (q *Queries) ExistsUserByEmail(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUserById = `-- name: ExistsUserById :one
SELECT EXISTS (
    SELECT 1
    FROM "AspNetUsers"
    WHERE "Id" = $1
) AS "exists"
`

func (q *Queries) ExistsUserById(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findUserPreferences = `-- name: FindUserPreferences :one
SELECT EXISTS (
    SELECT 1
    FROM "UserPreferences"
    WHERE "UserId" = $1
) AS "exists"
`

func (q *Queries) FindUserPreferences(ctx context.Context, userid pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, findUserPreferences, userid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getGeneratedCvById = `-- name: GetGeneratedCvById :one
SELECT "UserId", "JobId", "FileName", "ExtractedText"
FROM "GeneratedCvsNew" WHERE "Id" = $1
`

type GetGeneratedCvByIdRow struct {
	UserId        pgtype.UUID `db:"UserId" json:"UserId"`
	JobId         pgtype.UUID `db:"JobId" json:"JobId"`
	FileName      string      `db:"FileName" json:"FileName"`
	ExtractedText string      `db:"ExtractedText" json:"ExtractedText"`
}

func (q *Queries) GetGeneratedCvById(ctx context.Context, id pgtype.UUID) (GetGeneratedCvByIdRow, error) {
	row := q.db.QueryRow(ctx, getGeneratedCvById, id)
	var i GetGeneratedCvByIdRow
	err := row.Scan(
		&i.UserId,
		&i.JobId,
		&i.FileName,
		&i.ExtractedText,
	)
	return i, err
}

const getGeneratedCvs = `-- name: GetGeneratedCvs :many
SELECT "UserId", "JobId", j."Title", cv."FileName", "ExtractedText"
FROM "GeneratedCvsNew" as cv
LEFT JOIN "Jobs" as j ON cv."JobId" = j."Id" 
WHERE "UserId" = $1
`

type GetGeneratedCvsRow struct {
	UserId        pgtype.UUID `db:"UserId" json:"UserId"`
	JobId         pgtype.UUID `db:"JobId" json:"JobId"`
	Title         pgtype.Text `db:"Title" json:"Title"`
	FileName      string      `db:"FileName" json:"FileName"`
	ExtractedText string      `db:"ExtractedText" json:"ExtractedText"`
}

func (q *Queries) GetGeneratedCvs(ctx context.Context, userid pgtype.UUID) ([]GetGeneratedCvsRow, error) {
	rows, err := q.db.Query(ctx, getGeneratedCvs, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGeneratedCvsRow
	for rows.Next() {
		var i GetGeneratedCvsRow
		if err := rows.Scan(
			&i.UserId,
			&i.JobId,
			&i.Title,
			&i.FileName,
			&i.ExtractedText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobById = `-- name: GetJobById :one
SELECT "Id", 
    "Title", 
    "Platform", 
    "Company", 
    "Description",
    "Url", 
    "IsApplied", 
    "Status", 
    "Active" 
FROM "Jobs" 
WHERE "Id" = $1
`

type GetJobByIdRow struct {
	Id          pgtype.UUID `db:"Id" json:"Id"`
	Title       string      `db:"Title" json:"Title"`
	Platform    string      `db:"Platform" json:"Platform"`
	Company     string      `db:"Company" json:"Company"`
	Description string      `db:"Description" json:"Description"`
	Url         string      `db:"Url" json:"Url"`
	IsApplied   bool        `db:"IsApplied" json:"IsApplied"`
	Status      string      `db:"Status" json:"Status"`
	Active      bool        `db:"Active" json:"Active"`
}

func (q *Queries) GetJobById(ctx context.Context, id pgtype.UUID) (GetJobByIdRow, error) {
	row := q.db.QueryRow(ctx, getJobById, id)
	var i GetJobByIdRow
	err := row.Scan(
		&i.Id,
		&i.Title,
		&i.Platform,
		&i.Company,
		&i.Description,
		&i.Url,
		&i.IsApplied,
		&i.Status,
		&i.Active,
	)
	return i, err
}

const getJobs = `-- name: GetJobs :many
SELECT DISTINCT j."Id", j."PlataformJobId", j."Title", j."Description", j."Url", j."IsApplied", j."Status", j."Active", j."CreatedBy", j."CreatedAt", j."LastModifiedBy", j."LastModifiedAt", j."Platform", j."Company"
FROM "Jobs" j
WHERE EXISTS (
    SELECT 1
    FROM "UserSearchQueries" usq
    JOIN "SearchQueries" sq
        ON sq."Id" = usq."SearchQueryId"
    CROSS JOIN LATERAL unnest(sq."Keywords") AS keyword
    WHERE usq."UserId" = $1
      AND j."Title" ILIKE '%' || keyword || '%'
)
`

func (q *Queries) GetJobs(ctx context.Context, userid pgtype.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobs, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Id,
			&i.PlataformJobId,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.IsApplied,
			&i.Status,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
			&i.Platform,
			&i.Company,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT "Id", "Name", "CPF", "Email", "PasswordHash", "AccessFailedCount", "OnboardingCompleted", "LockoutEnd", "LockoutEnabled", "TwoFactorEnabled", "EmailConfirmed", "PhoneNumberConfirmed" 
FROM public."AspNetUsers"
WHERE "Email" = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (AspNetUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AspNetUser
	err := row.Scan(
		&i.Id,
		&i.Name,
		&i.CPF,
		&i.Email,
		&i.PasswordHash,
		&i.AccessFailedCount,
		&i.OnboardingCompleted,
		&i.LockoutEnd,
		&i.LockoutEnabled,
		&i.TwoFactorEnabled,
		&i.EmailConfirmed,
		&i.PhoneNumberConfirmed,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT "Id", "Name", "CPF", "Email", "PasswordHash", "AccessFailedCount", "OnboardingCompleted", "LockoutEnd", "LockoutEnabled", "TwoFactorEnabled", "EmailConfirmed", "PhoneNumberConfirmed" 
FROM public."AspNetUsers"
WHERE "Id" = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (AspNetUser, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i AspNetUser
	err := row.Scan(
		&i.Id,
		&i.Name,
		&i.CPF,
		&i.Email,
		&i.PasswordHash,
		&i.AccessFailedCount,
		&i.OnboardingCompleted,
		&i.LockoutEnd,
		&i.LockoutEnabled,
		&i.TwoFactorEnabled,
		&i.EmailConfirmed,
		&i.PhoneNumberConfirmed,
	)
	return i, err
}

const getUserCv = `-- name: GetUserCv :one
SELECT "UserId", 
"UrlFile", 
"ExtractedText", 
"Active", 
"CreatedBy", 
"CreatedAt", 
"LastModifiedBy", 
"LastModifiedAt" 
FROM "UserCvs" WHERE "UserId" = $1
`

type GetUserCvRow struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	UrlFile        string             `db:"UrlFile" json:"UrlFile"`
	ExtractedText  string             `db:"ExtractedText" json:"ExtractedText"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) GetUserCv(ctx context.Context, userid pgtype.UUID) (GetUserCvRow, error) {
	row := q.db.QueryRow(ctx, getUserCv, userid)
	var i GetUserCvRow
	err := row.Scan(
		&i.UserId,
		&i.UrlFile,
		&i.ExtractedText,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :many
SELECT "UserId", 
        "Skills", 
        "Levels" 
FROM "UserPreferences" 
WHERE "UserId" = $1 AND "Active" = true
`

type GetUserPreferencesRow struct {
	UserId pgtype.UUID `db:"UserId" json:"UserId"`
	Skills []string    `db:"Skills" json:"Skills"`
	Levels []string    `db:"Levels" json:"Levels"`
}

func (q *Queries) GetUserPreferences(ctx context.Context, userid pgtype.UUID) ([]GetUserPreferencesRow, error) {
	rows, err := q.db.Query(ctx, getUserPreferences, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPreferencesRow
	for rows.Next() {
		var i GetUserPreferencesRow
		if err := rows.Scan(&i.UserId, &i.Skills, &i.Levels); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveGeneratedCV = `-- name: SaveGeneratedCV :exec
INSERT INTO "GeneratedCvsNew" ("UserId", "JobId", "FileName", "ExtractedText", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type SaveGeneratedCVParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	JobId          pgtype.UUID        `db:"JobId" json:"JobId"`
	FileName       string             `db:"FileName" json:"FileName"`
	ExtractedText  string             `db:"ExtractedText" json:"ExtractedText"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) SaveGeneratedCV(ctx context.Context, arg SaveGeneratedCVParams) error {
	_, err := q.db.Exec(ctx, saveGeneratedCV,
		arg.UserId,
		arg.JobId,
		arg.FileName,
		arg.ExtractedText,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const saveUserCv = `-- name: SaveUserCv :exec
INSERT INTO "UserCvs" ("UserId", "UrlFile", "ExtractedText", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SaveUserCvParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	UrlFile        string             `db:"UrlFile" json:"UrlFile"`
	ExtractedText  string             `db:"ExtractedText" json:"ExtractedText"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) SaveUserCv(ctx context.Context, arg SaveUserCvParams) error {
	_, err := q.db.Exec(ctx, saveUserCv,
		arg.UserId,
		arg.UrlFile,
		arg.ExtractedText,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE "UserPreferences" 
SET "UserId" = $1, "Skills" = $2, "Levels" = $3, "Active" = $4, "LastModifiedBy" = $5, "LastModifiedAt" = $6 
WHERE "UserId" = $1
`

type UpdateUserPreferencesParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	Skills         []string           `db:"Skills" json:"Skills"`
	Levels         []string           `db:"Levels" json:"Levels"`
	Active         bool               `db:"Active" json:"Active"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferences,
		arg.UserId,
		arg.Skills,
		arg.Levels,
		arg.Active,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}
