// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJobs = `-- name: GetJobs :many
SELECT 
    title,
    description,
    url,
    isApplied,
    status,
    active,
    platform,
    company
FROM jobs
`

type GetJobsRow struct {
	Title       string `db:"title" json:"title"`
	Description string `db:"description" json:"description"`
	Url         string `db:"url" json:"url"`
	Isapplied   bool   `db:"isapplied" json:"isapplied"`
	Status      string `db:"status" json:"status"`
	Active      bool   `db:"active" json:"active"`
	Platform    string `db:"platform" json:"platform"`
	Company     string `db:"company" json:"company"`
}

func (q *Queries) GetJobs(ctx context.Context) ([]GetJobsRow, error) {
	rows, err := q.db.Query(ctx, getJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJobsRow
	for rows.Next() {
		var i GetJobsRow
		if err := rows.Scan(
			&i.Title,
			&i.Description,
			&i.Url,
			&i.Isapplied,
			&i.Status,
			&i.Active,
			&i.Platform,
			&i.Company,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, cpf, email, passwordHash, accessFailedCount, onboardingCompleted
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cpf,
		&i.Email,
		&i.Passwordhash,
		&i.Accessfailedcount,
		&i.Onboardingcompleted,
	)
	return i, err
}
