// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO author (name, cpf)
VALUES (lower($1), $2)
RETURNING id, name, cpf
`

type CreateAuthorParams struct {
	Name string `db:"name" json:"name"`
	Cpf  string `db:"cpf" json:"cpf"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.Cpf)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Cpf)
	return i, err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, cpf
FROM author
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, id int32) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Cpf)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, cpf
FROM author
ORDER BY name
`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.Cpf); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
