// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :exec
INSERT INTO "Applications" ("UserId", "JobId", "Status", "Obs", "Platform", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateApplicationParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	JobId          pgtype.UUID        `db:"JobId" json:"JobId"`
	Status         string             `db:"Status" json:"Status"`
	Obs            pgtype.Text        `db:"Obs" json:"Obs"`
	Platform       pgtype.Text        `db:"Platform" json:"Platform"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) error {
	_, err := q.db.Exec(ctx, createApplication,
		arg.UserId,
		arg.JobId,
		arg.Status,
		arg.Obs,
		arg.Platform,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const createApplicationRate = `-- name: CreateApplicationRate :exec
INSERT INTO "ApplicationEvaluations" ("UserId", "ApplicationId", "Liked", "Feedback", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateApplicationRateParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	ApplicationId  pgtype.UUID        `db:"ApplicationId" json:"ApplicationId"`
	Liked          bool               `db:"Liked" json:"Liked"`
	Feedback       pgtype.Text        `db:"Feedback" json:"Feedback"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) CreateApplicationRate(ctx context.Context, arg CreateApplicationRateParams) error {
	_, err := q.db.Exec(ctx, createApplicationRate,
		arg.UserId,
		arg.ApplicationId,
		arg.Liked,
		arg.Feedback,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO "PasswordResetTokens" ("Email", "TokenHash", "ExpiresAt")
VALUES ($1, $2, $3)
`

type CreatePasswordResetTokenParams struct {
	Email     string             `db:"Email" json:"Email"`
	TokenHash string             `db:"TokenHash" json:"TokenHash"`
	ExpiresAt pgtype.Timestamptz `db:"ExpiresAt" json:"ExpiresAt"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.Email, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createQuestion = `-- name: CreateQuestion :exec
INSERT INTO "Questions" ("UserId", "JobId", "Question", "Answer", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateQuestionParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	JobId          pgtype.UUID        `db:"JobId" json:"JobId"`
	Question       string             `db:"Question" json:"Question"`
	Answer         string             `db:"Answer" json:"Answer"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) error {
	_, err := q.db.Exec(ctx, createQuestion,
		arg.UserId,
		arg.JobId,
		arg.Question,
		arg.Answer,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const createSearchQuery = `-- name: CreateSearchQuery :one
INSERT INTO "SearchQueries" ("Query", "Keywords", "NormalizedHash", "Area", "Levels", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "Id"
`

type CreateSearchQueryParams struct {
	Query          string             `db:"Query" json:"Query"`
	Keywords       []string           `db:"Keywords" json:"Keywords"`
	NormalizedHash string             `db:"NormalizedHash" json:"NormalizedHash"`
	Area           string             `db:"Area" json:"Area"`
	Levels         []string           `db:"Levels" json:"Levels"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) CreateSearchQuery(ctx context.Context, arg CreateSearchQueryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSearchQuery,
		arg.Query,
		arg.Keywords,
		arg.NormalizedHash,
		arg.Area,
		arg.Levels,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	var Id pgtype.UUID
	err := row.Scan(&Id)
	return Id, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO "AspNetUsers" ("Name", "CPF", "Email", "PasswordHash", "AccessFailedCount", "OnboardingCompleted", "TwoFactorEnabled", "EmailConfirmed", "PhoneNumberConfirmed", "LockoutEnabled")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateUserParams struct {
	Name                 string      `db:"Name" json:"Name"`
	CPF                  string      `db:"CPF" json:"CPF"`
	Email                pgtype.Text `db:"Email" json:"Email"`
	PasswordHash         pgtype.Text `db:"PasswordHash" json:"PasswordHash"`
	AccessFailedCount    int32       `db:"AccessFailedCount" json:"AccessFailedCount"`
	OnboardingCompleted  bool        `db:"OnboardingCompleted" json:"OnboardingCompleted"`
	TwoFactorEnabled     bool        `db:"TwoFactorEnabled" json:"TwoFactorEnabled"`
	EmailConfirmed       bool        `db:"EmailConfirmed" json:"EmailConfirmed"`
	PhoneNumberConfirmed bool        `db:"PhoneNumberConfirmed" json:"PhoneNumberConfirmed"`
	LockoutEnabled       bool        `db:"LockoutEnabled" json:"LockoutEnabled"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Name,
		arg.CPF,
		arg.Email,
		arg.PasswordHash,
		arg.AccessFailedCount,
		arg.OnboardingCompleted,
		arg.TwoFactorEnabled,
		arg.EmailConfirmed,
		arg.PhoneNumberConfirmed,
		arg.LockoutEnabled,
	)
	return err
}

const createUserPreferences = `-- name: CreateUserPreferences :exec
INSERT INTO "UserPreferences" ("UserId", "Skills", "Levels", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateUserPreferencesParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	Skills         []string           `db:"Skills" json:"Skills"`
	Levels         []string           `db:"Levels" json:"Levels"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, createUserPreferences,
		arg.UserId,
		arg.Skills,
		arg.Levels,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const createUserSearchQuery = `-- name: CreateUserSearchQuery :exec
INSERT INTO "UserSearchQueries" ("UserId", "SearchQueryId", "CreatedAt")
VALUES ($1, $2, $3)
`

type CreateUserSearchQueryParams struct {
	UserId        pgtype.UUID        `db:"UserId" json:"UserId"`
	SearchQueryId pgtype.UUID        `db:"SearchQueryId" json:"SearchQueryId"`
	CreatedAt     pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
}

func (q *Queries) CreateUserSearchQuery(ctx context.Context, arg CreateUserSearchQueryParams) error {
	_, err := q.db.Exec(ctx, createUserSearchQuery, arg.UserId, arg.SearchQueryId, arg.CreatedAt)
	return err
}

const evaluateCv = `-- name: EvaluateCv :exec
INSERT INTO "CvEvaluations" ("UserId", "GeneratedCvId", "Liked", "Feedback", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type EvaluateCvParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	GeneratedCvId  pgtype.UUID        `db:"GeneratedCvId" json:"GeneratedCvId"`
	Liked          bool               `db:"Liked" json:"Liked"`
	Feedback       pgtype.Text        `db:"Feedback" json:"Feedback"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) EvaluateCv(ctx context.Context, arg EvaluateCvParams) error {
	_, err := q.db.Exec(ctx, evaluateCv,
		arg.UserId,
		arg.GeneratedCvId,
		arg.Liked,
		arg.Feedback,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const evaluateJob = `-- name: EvaluateJob :exec
INSERT INTO "JobEvaluations" ("UserId", "JobId", "Liked", "Feedback", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type EvaluateJobParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	JobId          pgtype.UUID        `db:"JobId" json:"JobId"`
	Liked          bool               `db:"Liked" json:"Liked"`
	Feedback       pgtype.Text        `db:"Feedback" json:"Feedback"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) EvaluateJob(ctx context.Context, arg EvaluateJobParams) error {
	_, err := q.db.Exec(ctx, evaluateJob,
		arg.UserId,
		arg.JobId,
		arg.Liked,
		arg.Feedback,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const existsCvEvaluation = `-- name: ExistsCvEvaluation :one
SELECT EXISTS (
    SELECT 1
    FROM "CvEvaluations"
    WHERE "UserId" = $1 AND "GeneratedCvId" = $2
) AS "exists"
`

type ExistsCvEvaluationParams struct {
	UserId        pgtype.UUID `db:"UserId" json:"UserId"`
	GeneratedCvId pgtype.UUID `db:"GeneratedCvId" json:"GeneratedCvId"`
}

func (q *Queries) ExistsCvEvaluation(ctx context.Context, arg ExistsCvEvaluationParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsCvEvaluation, arg.UserId, arg.GeneratedCvId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsJobEvaluation = `-- name: ExistsJobEvaluation :one
SELECT EXISTS (
    SELECT 1
    FROM "JobEvaluations"
    WHERE "UserId" = $1 AND "JobId" = $2
) AS "exists"
`

type ExistsJobEvaluationParams struct {
	UserId pgtype.UUID `db:"UserId" json:"UserId"`
	JobId  pgtype.UUID `db:"JobId" json:"JobId"`
}

func (q *Queries) ExistsJobEvaluation(ctx context.Context, arg ExistsJobEvaluationParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsJobEvaluation, arg.UserId, arg.JobId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsSearchQueryByAnotherUser = `-- name: ExistsSearchQueryByAnotherUser :one
SELECT EXISTS (
    SELECT 1
    FROM "UserSearchQueries"
    WHERE "SearchQueryId" = $1
    AND "UserId" != $2
) AS "exists"
`

type ExistsSearchQueryByAnotherUserParams struct {
	SearchQueryId pgtype.UUID `db:"SearchQueryId" json:"SearchQueryId"`
	UserId        pgtype.UUID `db:"UserId" json:"UserId"`
}

func (q *Queries) ExistsSearchQueryByAnotherUser(ctx context.Context, arg ExistsSearchQueryByAnotherUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsSearchQueryByAnotherUser, arg.SearchQueryId, arg.UserId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsSearchQueryByUserId = `-- name: ExistsSearchQueryByUserId :one
SELECT EXISTS (
    SELECT 1
    FROM "UserSearchQueries"
    WHERE "UserId" = $1
) AS "exists"
`

func (q *Queries) ExistsSearchQueryByUserId(ctx context.Context, userid pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsSearchQueryByUserId, userid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUserByEmail = `-- name: ExistsUserByEmail :one
SELECT EXISTS (
    SELECT 1
    FROM "AspNetUsers"
    WHERE "Email" = $1
) AS "exists"
`

func (q *Queries) ExistsUserByEmail(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUserById = `-- name: ExistsUserById :one
SELECT EXISTS (
    SELECT 1
    FROM "AspNetUsers"
    WHERE "Id" = $1
) AS "exists"
`

func (q *Queries) ExistsUserById(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findQuestionAnswer = `-- name: FindQuestionAnswer :many
SELECT "Question", 
    "Answer"
FROM "Questions"
WHERE "Question" = ANY($1::text[])
`

type FindQuestionAnswerRow struct {
	Question string `db:"Question" json:"Question"`
	Answer   string `db:"Answer" json:"Answer"`
}

func (q *Queries) FindQuestionAnswer(ctx context.Context, questions []string) ([]FindQuestionAnswerRow, error) {
	rows, err := q.db.Query(ctx, findQuestionAnswer, questions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindQuestionAnswerRow
	for rows.Next() {
		var i FindQuestionAnswerRow
		if err := rows.Scan(&i.Question, &i.Answer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserPreferences = `-- name: FindUserPreferences :one
SELECT EXISTS (
    SELECT 1
    FROM "UserPreferences"
    WHERE "UserId" = $1
) AS "exists"
`

func (q *Queries) FindUserPreferences(ctx context.Context, userid pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, findUserPreferences, userid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getApplicationsPerDay = `-- name: GetApplicationsPerDay :many
SELECT j."CreatedAt"::date AS date, COUNT(*)::int AS count
FROM "Jobs" j
WHERE EXISTS (
    SELECT 1 FROM "UserSearchQueries" usq
    JOIN "SearchQueries" sq ON sq."Id" = usq."SearchQueryId"
    CROSS JOIN LATERAL unnest(sq."Keywords") AS keyword
    WHERE usq."UserId" = $1
    AND j."Title" ILIKE '%' || keyword || '%'
)
AND j."CreatedAt" >= CURRENT_DATE - INTERVAL '6 days'
GROUP BY j."CreatedAt"::date
ORDER BY j."CreatedAt"::date
`

type GetApplicationsPerDayRow struct {
	Date  pgtype.Date `db:"date" json:"date"`
	Count int32       `db:"count" json:"count"`
}

func (q *Queries) GetApplicationsPerDay(ctx context.Context, userid pgtype.UUID) ([]GetApplicationsPerDayRow, error) {
	rows, err := q.db.Query(ctx, getApplicationsPerDay, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplicationsPerDayRow
	for rows.Next() {
		var i GetApplicationsPerDayRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGeneratedCvById = `-- name: GetGeneratedCvById :one
SELECT "UserId", "JobId", "FileName", "ExtractedText"
FROM "GeneratedCvsNew" WHERE "Id" = $1
`

type GetGeneratedCvByIdRow struct {
	UserId        pgtype.UUID `db:"UserId" json:"UserId"`
	JobId         pgtype.UUID `db:"JobId" json:"JobId"`
	FileName      string      `db:"FileName" json:"FileName"`
	ExtractedText string      `db:"ExtractedText" json:"ExtractedText"`
}

func (q *Queries) GetGeneratedCvById(ctx context.Context, id pgtype.UUID) (GetGeneratedCvByIdRow, error) {
	row := q.db.QueryRow(ctx, getGeneratedCvById, id)
	var i GetGeneratedCvByIdRow
	err := row.Scan(
		&i.UserId,
		&i.JobId,
		&i.FileName,
		&i.ExtractedText,
	)
	return i, err
}

const getGeneratedCvs = `-- name: GetGeneratedCvs :many
SELECT "UserId", "JobId", j."Title", cv."FileName", "ExtractedText"
FROM "GeneratedCvsNew" as cv
LEFT JOIN "Jobs" as j ON cv."JobId" = j."Id" 
WHERE "UserId" = $1
`

type GetGeneratedCvsRow struct {
	UserId        pgtype.UUID `db:"UserId" json:"UserId"`
	JobId         pgtype.UUID `db:"JobId" json:"JobId"`
	Title         pgtype.Text `db:"Title" json:"Title"`
	FileName      string      `db:"FileName" json:"FileName"`
	ExtractedText string      `db:"ExtractedText" json:"ExtractedText"`
}

func (q *Queries) GetGeneratedCvs(ctx context.Context, userid pgtype.UUID) ([]GetGeneratedCvsRow, error) {
	rows, err := q.db.Query(ctx, getGeneratedCvs, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGeneratedCvsRow
	for rows.Next() {
		var i GetGeneratedCvsRow
		if err := rows.Scan(
			&i.UserId,
			&i.JobId,
			&i.Title,
			&i.FileName,
			&i.ExtractedText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobById = `-- name: GetJobById :one
SELECT "Id", 
    "Title", 
    "Platform", 
    "Company", 
    "Description",
    "Url", 
    "IsApplied", 
    "Status", 
    "Active" 
FROM "Jobs" 
WHERE "Id" = $1
`

type GetJobByIdRow struct {
	Id          pgtype.UUID `db:"Id" json:"Id"`
	Title       string      `db:"Title" json:"Title"`
	Platform    string      `db:"Platform" json:"Platform"`
	Company     string      `db:"Company" json:"Company"`
	Description string      `db:"Description" json:"Description"`
	Url         string      `db:"Url" json:"Url"`
	IsApplied   bool        `db:"IsApplied" json:"IsApplied"`
	Status      string      `db:"Status" json:"Status"`
	Active      bool        `db:"Active" json:"Active"`
}

func (q *Queries) GetJobById(ctx context.Context, id pgtype.UUID) (GetJobByIdRow, error) {
	row := q.db.QueryRow(ctx, getJobById, id)
	var i GetJobByIdRow
	err := row.Scan(
		&i.Id,
		&i.Title,
		&i.Platform,
		&i.Company,
		&i.Description,
		&i.Url,
		&i.IsApplied,
		&i.Status,
		&i.Active,
	)
	return i, err
}

const getJobs = `-- name: GetJobs :many
SELECT DISTINCT j."Id", j."PlataformJobId", j."Title", j."Description", j."Url", j."IsApplied", j."Status", j."Active", j."CreatedBy", j."CreatedAt", j."LastModifiedBy", j."LastModifiedAt", j."Platform", j."Company"
FROM "Jobs" j
WHERE EXISTS (
    SELECT 1
    FROM "UserSearchQueries" usq
    JOIN "SearchQueries" sq
        ON sq."Id" = usq."SearchQueryId"
    CROSS JOIN LATERAL unnest(sq."Keywords") AS keyword
    WHERE usq."UserId" = $1
      AND j."Title" ILIKE '%' || keyword || '%'
) AND NOT EXISTS (
    SELECT 1
    FROM "Applications" a
    WHERE a."JobId" = j."Id"
) AND (
    $3::timestamptz IS NULL
    OR
    j."CreatedAt" < $3::timestamptz
)
ORDER BY "CreatedAt" DESC
LIMIT $2
`

type GetJobsParams struct {
	UserId pgtype.UUID        `db:"UserId" json:"UserId"`
	Limit  int32              `db:"limit" json:"limit"`
	Cursor pgtype.Timestamptz `db:"cursor" json:"cursor"`
}

func (q *Queries) GetJobs(ctx context.Context, arg GetJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobs, arg.UserId, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.Id,
			&i.PlataformJobId,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.IsApplied,
			&i.Status,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
			&i.Platform,
			&i.Company,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT "Id", "Email", "TokenHash", "ExpiresAt", "Used", "CreatedAt"
FROM "PasswordResetTokens"
WHERE "TokenHash" = $1 AND "Used" = false AND "ExpiresAt" > now()
LIMIT 1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenhash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenhash)
	var i PasswordResetToken
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformDistribution = `-- name: GetPlatformDistribution :many
SELECT j."Platform" AS platform, COUNT(*)::int AS count
FROM "Jobs" j
WHERE EXISTS (
    SELECT 1 FROM "UserSearchQueries" usq
    JOIN "SearchQueries" sq ON sq."Id" = usq."SearchQueryId"
    CROSS JOIN LATERAL unnest(sq."Keywords") AS keyword
    WHERE usq."UserId" = $1
    AND j."Title" ILIKE '%' || keyword || '%'
)
GROUP BY j."Platform"
ORDER BY COUNT(*) DESC
`

type GetPlatformDistributionRow struct {
	Platform string `db:"platform" json:"platform"`
	Count    int32  `db:"count" json:"count"`
}

func (q *Queries) GetPlatformDistribution(ctx context.Context, userid pgtype.UUID) ([]GetPlatformDistributionRow, error) {
	rows, err := q.db.Query(ctx, getPlatformDistribution, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlatformDistributionRow
	for rows.Next() {
		var i GetPlatformDistributionRow
		if err := rows.Scan(&i.Platform, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrevMonthJobCount = `-- name: GetPrevMonthJobCount :one
SELECT COUNT(*)::int AS count
FROM "Jobs" j
WHERE EXISTS (
    SELECT 1 FROM "UserSearchQueries" usq
    JOIN "SearchQueries" sq ON sq."Id" = usq."SearchQueryId"
    CROSS JOIN LATERAL unnest(sq."Keywords") AS keyword
    WHERE usq."UserId" = $1
    AND j."Title" ILIKE '%' || keyword || '%'
)
AND j."CreatedAt" >= date_trunc('month', CURRENT_DATE - INTERVAL '1 month')
AND j."CreatedAt" < date_trunc('month', CURRENT_DATE)
`

func (q *Queries) GetPrevMonthJobCount(ctx context.Context, userid pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getPrevMonthJobCount, userid)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getQuestionById = `-- name: GetQuestionById :one
SELECT q."Question",
    q."Answer",
    q."UserId"
FROM "Questions" AS q
WHERE "Id" = $1 AND q."Active" = true
`

type GetQuestionByIdRow struct {
	Question string      `db:"Question" json:"Question"`
	Answer   string      `db:"Answer" json:"Answer"`
	UserId   pgtype.UUID `db:"UserId" json:"UserId"`
}

func (q *Queries) GetQuestionById(ctx context.Context, id pgtype.UUID) (GetQuestionByIdRow, error) {
	row := q.db.QueryRow(ctx, getQuestionById, id)
	var i GetQuestionByIdRow
	err := row.Scan(&i.Question, &i.Answer, &i.UserId)
	return i, err
}

const getSearchQueryByUserId = `-- name: GetSearchQueryByUserId :one
SELECT sq."Id", sq."Query", sq."Keywords", sq."NormalizedHash", sq."Levels"
FROM "SearchQueries" AS sq
LEFT JOIN "UserSearchQueries" AS usq ON usq."SearchQueryId" = sq."Id"
WHERE usq."UserId" = $1
`

type GetSearchQueryByUserIdRow struct {
	Id             pgtype.UUID `db:"Id" json:"Id"`
	Query          string      `db:"Query" json:"Query"`
	Keywords       []string    `db:"Keywords" json:"Keywords"`
	NormalizedHash string      `db:"NormalizedHash" json:"NormalizedHash"`
	Levels         []string    `db:"Levels" json:"Levels"`
}

func (q *Queries) GetSearchQueryByUserId(ctx context.Context, userid pgtype.UUID) (GetSearchQueryByUserIdRow, error) {
	row := q.db.QueryRow(ctx, getSearchQueryByUserId, userid)
	var i GetSearchQueryByUserIdRow
	err := row.Scan(
		&i.Id,
		&i.Query,
		&i.Keywords,
		&i.NormalizedHash,
		&i.Levels,
	)
	return i, err
}

const getSearchQueryIdByUserId = `-- name: GetSearchQueryIdByUserId :one
SELECT "SearchQueryId" FROM "UserSearchQueries"
WHERE "UserId" = $1
`

func (q *Queries) GetSearchQueryIdByUserId(ctx context.Context, userid pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSearchQueryIdByUserId, userid)
	var SearchQueryId pgtype.UUID
	err := row.Scan(&SearchQueryId)
	return SearchQueryId, err
}

const getUserApplications = `-- name: GetUserApplications :many
SELECT a."Status",
    a."Obs",
    a."Platform",
    j."Title",
    a."CreatedAt"
FROM "Applications" AS a
LEFT JOIN "Jobs" AS j ON j."Id" = a."JobId"
WHERE a."UserId" = $1
`

type GetUserApplicationsRow struct {
	Status    string             `db:"Status" json:"Status"`
	Obs       pgtype.Text        `db:"Obs" json:"Obs"`
	Platform  pgtype.Text        `db:"Platform" json:"Platform"`
	Title     pgtype.Text        `db:"Title" json:"Title"`
	CreatedAt pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
}

func (q *Queries) GetUserApplications(ctx context.Context, userid pgtype.UUID) ([]GetUserApplicationsRow, error) {
	rows, err := q.db.Query(ctx, getUserApplications, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserApplicationsRow
	for rows.Next() {
		var i GetUserApplicationsRow
		if err := rows.Scan(
			&i.Status,
			&i.Obs,
			&i.Platform,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT "Id", "Name", "CPF", "Email", "PasswordHash", "AccessFailedCount", "OnboardingCompleted", "LockoutEnd", "LockoutEnabled", "TwoFactorEnabled", "EmailConfirmed", "PhoneNumberConfirmed" 
FROM public."AspNetUsers"
WHERE "Email" = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (AspNetUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AspNetUser
	err := row.Scan(
		&i.Id,
		&i.Name,
		&i.CPF,
		&i.Email,
		&i.PasswordHash,
		&i.AccessFailedCount,
		&i.OnboardingCompleted,
		&i.LockoutEnd,
		&i.LockoutEnabled,
		&i.TwoFactorEnabled,
		&i.EmailConfirmed,
		&i.PhoneNumberConfirmed,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT "Id", "Name", "CPF", "Email", "PasswordHash", "AccessFailedCount", "OnboardingCompleted", "LockoutEnd", "LockoutEnabled", "TwoFactorEnabled", "EmailConfirmed", "PhoneNumberConfirmed" 
FROM public."AspNetUsers"
WHERE "Id" = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (AspNetUser, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i AspNetUser
	err := row.Scan(
		&i.Id,
		&i.Name,
		&i.CPF,
		&i.Email,
		&i.PasswordHash,
		&i.AccessFailedCount,
		&i.OnboardingCompleted,
		&i.LockoutEnd,
		&i.LockoutEnabled,
		&i.TwoFactorEnabled,
		&i.EmailConfirmed,
		&i.PhoneNumberConfirmed,
	)
	return i, err
}

const getUserCv = `-- name: GetUserCv :one
SELECT "UserId", 
"UrlFile", 
"ExtractedText", 
"Active", 
"CreatedBy", 
"CreatedAt", 
"LastModifiedBy", 
"LastModifiedAt" 
FROM "UserCvs" WHERE "UserId" = $1
`

type GetUserCvRow struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	UrlFile        string             `db:"UrlFile" json:"UrlFile"`
	ExtractedText  string             `db:"ExtractedText" json:"ExtractedText"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) GetUserCv(ctx context.Context, userid pgtype.UUID) (GetUserCvRow, error) {
	row := q.db.QueryRow(ctx, getUserCv, userid)
	var i GetUserCvRow
	err := row.Scan(
		&i.UserId,
		&i.UrlFile,
		&i.ExtractedText,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const getUserJobStats = `-- name: GetUserJobStats :one
SELECT
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE j."IsApplied" = true)::int AS applied,
    COUNT(*) FILTER (WHERE j."IsApplied" = false)::int AS skipped
FROM "Jobs" j
WHERE EXISTS (
    SELECT 1 FROM "UserSearchQueries" usq
    JOIN "SearchQueries" sq ON sq."Id" = usq."SearchQueryId"
    CROSS JOIN LATERAL unnest(sq."Keywords") AS keyword
    WHERE usq."UserId" = $1
    AND j."Title" ILIKE '%' || keyword || '%'
)
`

type GetUserJobStatsRow struct {
	Total   int32 `db:"total" json:"total"`
	Applied int32 `db:"applied" json:"applied"`
	Skipped int32 `db:"skipped" json:"skipped"`
}

func (q *Queries) GetUserJobStats(ctx context.Context, userid pgtype.UUID) (GetUserJobStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserJobStats, userid)
	var i GetUserJobStatsRow
	err := row.Scan(&i.Total, &i.Applied, &i.Skipped)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :many
SELECT "UserId", 
        "Skills", 
        "Levels" 
FROM "UserPreferences" 
WHERE "UserId" = $1 AND "Active" = true
`

type GetUserPreferencesRow struct {
	UserId pgtype.UUID `db:"UserId" json:"UserId"`
	Skills []string    `db:"Skills" json:"Skills"`
	Levels []string    `db:"Levels" json:"Levels"`
}

func (q *Queries) GetUserPreferences(ctx context.Context, userid pgtype.UUID) ([]GetUserPreferencesRow, error) {
	rows, err := q.db.Query(ctx, getUserPreferences, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPreferencesRow
	for rows.Next() {
		var i GetUserPreferencesRow
		if err := rows.Scan(&i.UserId, &i.Skills, &i.Levels); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserQuestions = `-- name: GetUserQuestions :many
SELECT q."Question",
    q."Answer",
    j."Title"
FROM "Questions" AS q
LEFT JOIN "Jobs" AS j ON j."Id" = q."JobId"
WHERE "UserId" = $1 AND q."Active" = true
`

type GetUserQuestionsRow struct {
	Question string      `db:"Question" json:"Question"`
	Answer   string      `db:"Answer" json:"Answer"`
	Title    pgtype.Text `db:"Title" json:"Title"`
}

func (q *Queries) GetUserQuestions(ctx context.Context, userid pgtype.UUID) ([]GetUserQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getUserQuestions, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserQuestionsRow
	for rows.Next() {
		var i GetUserQuestionsRow
		if err := rows.Scan(&i.Question, &i.Answer, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markResetTokenAsUsed = `-- name: MarkResetTokenAsUsed :exec
UPDATE "PasswordResetTokens" SET "Used" = true WHERE "Id" = $1
`

func (q *Queries) MarkResetTokenAsUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markResetTokenAsUsed, id)
	return err
}

const saveGeneratedCV = `-- name: SaveGeneratedCV :exec
INSERT INTO "GeneratedCvsNew" ("UserId", "JobId", "FileName", "ExtractedText", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type SaveGeneratedCVParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	JobId          pgtype.UUID        `db:"JobId" json:"JobId"`
	FileName       string             `db:"FileName" json:"FileName"`
	ExtractedText  string             `db:"ExtractedText" json:"ExtractedText"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) SaveGeneratedCV(ctx context.Context, arg SaveGeneratedCVParams) error {
	_, err := q.db.Exec(ctx, saveGeneratedCV,
		arg.UserId,
		arg.JobId,
		arg.FileName,
		arg.ExtractedText,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const saveUserCv = `-- name: SaveUserCv :exec
INSERT INTO "UserCvs" ("UserId", "UrlFile", "ExtractedText", "Active", "CreatedBy", "CreatedAt", "LastModifiedBy", "LastModifiedAt") 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SaveUserCvParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	UrlFile        string             `db:"UrlFile" json:"UrlFile"`
	ExtractedText  string             `db:"ExtractedText" json:"ExtractedText"`
	Active         bool               `db:"Active" json:"Active"`
	CreatedBy      string             `db:"CreatedBy" json:"CreatedBy"`
	CreatedAt      pgtype.Timestamptz `db:"CreatedAt" json:"CreatedAt"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) SaveUserCv(ctx context.Context, arg SaveUserCvParams) error {
	_, err := q.db.Exec(ctx, saveUserCv,
		arg.UserId,
		arg.UrlFile,
		arg.ExtractedText,
		arg.Active,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const updateQuestionAnswer = `-- name: UpdateQuestionAnswer :exec
UPDATE "Questions" SET "Answer" = $2 WHERE "Id" = $1
`

type UpdateQuestionAnswerParams struct {
	Id     pgtype.UUID `db:"Id" json:"Id"`
	Answer string      `db:"Answer" json:"Answer"`
}

func (q *Queries) UpdateQuestionAnswer(ctx context.Context, arg UpdateQuestionAnswerParams) error {
	_, err := q.db.Exec(ctx, updateQuestionAnswer, arg.Id, arg.Answer)
	return err
}

const updateSearchQuery = `-- name: UpdateSearchQuery :exec
UPDATE "SearchQueries" SET "Query" = $1, "Keywords" = $2, "NormalizedHash" = $3, "Levels" = $4, "LastModifiedBy" = $5, "LastModifiedAt" = $6
FROM "UserSearchQueries" AS usq
WHERE usq."UserId" = $7 AND usq."SearchQueryId" = "SearchQueries"."Id"
`

type UpdateSearchQueryParams struct {
	Query          string             `db:"Query" json:"Query"`
	Keywords       []string           `db:"Keywords" json:"Keywords"`
	NormalizedHash string             `db:"NormalizedHash" json:"NormalizedHash"`
	Levels         []string           `db:"Levels" json:"Levels"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
}

func (q *Queries) UpdateSearchQuery(ctx context.Context, arg UpdateSearchQueryParams) error {
	_, err := q.db.Exec(ctx, updateSearchQuery,
		arg.Query,
		arg.Keywords,
		arg.NormalizedHash,
		arg.Levels,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
		arg.UserId,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "AspNetUsers"
SET "Name" = $2, "CPF" = $3, "Email" = $4
WHERE "Id" = $1
`

type UpdateUserParams struct {
	Id    pgtype.UUID `db:"Id" json:"Id"`
	Name  string      `db:"Name" json:"Name"`
	CPF   string      `db:"CPF" json:"CPF"`
	Email pgtype.Text `db:"Email" json:"Email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Id,
		arg.Name,
		arg.CPF,
		arg.Email,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE "AspNetUsers"
SET "PasswordHash" = $2
WHERE "Id" = $1
`

type UpdateUserPasswordParams struct {
	Id           pgtype.UUID `db:"Id" json:"Id"`
	PasswordHash pgtype.Text `db:"PasswordHash" json:"PasswordHash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Id, arg.PasswordHash)
	return err
}

const updateUserPasswordByEmail = `-- name: UpdateUserPasswordByEmail :exec
UPDATE "AspNetUsers" SET "PasswordHash" = $2 WHERE "Email" = $1
`

type UpdateUserPasswordByEmailParams struct {
	Email        pgtype.Text `db:"Email" json:"Email"`
	PasswordHash pgtype.Text `db:"PasswordHash" json:"PasswordHash"`
}

func (q *Queries) UpdateUserPasswordByEmail(ctx context.Context, arg UpdateUserPasswordByEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordByEmail, arg.Email, arg.PasswordHash)
	return err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE "UserPreferences" 
SET "UserId" = $1, "Skills" = $2, "Levels" = $3, "Active" = $4, "LastModifiedBy" = $5, "LastModifiedAt" = $6 
WHERE "UserId" = $1
`

type UpdateUserPreferencesParams struct {
	UserId         pgtype.UUID        `db:"UserId" json:"UserId"`
	Skills         []string           `db:"Skills" json:"Skills"`
	Levels         []string           `db:"Levels" json:"Levels"`
	Active         bool               `db:"Active" json:"Active"`
	LastModifiedBy string             `db:"LastModifiedBy" json:"LastModifiedBy"`
	LastModifiedAt pgtype.Timestamptz `db:"LastModifiedAt" json:"LastModifiedAt"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferences,
		arg.UserId,
		arg.Skills,
		arg.Levels,
		arg.Active,
		arg.LastModifiedBy,
		arg.LastModifiedAt,
	)
	return err
}

const updateUserSearchQuery = `-- name: UpdateUserSearchQuery :exec
UPDATE "UserSearchQueries" SET "SearchQueryId" = $2
WHERE "UserId" = $1
`

type UpdateUserSearchQueryParams struct {
	UserId        pgtype.UUID `db:"UserId" json:"UserId"`
	SearchQueryId pgtype.UUID `db:"SearchQueryId" json:"SearchQueryId"`
}

func (q *Queries) UpdateUserSearchQuery(ctx context.Context, arg UpdateUserSearchQueryParams) error {
	_, err := q.db.Exec(ctx, updateUserSearchQuery, arg.UserId, arg.SearchQueryId)
	return err
}
